minApprovals:
 COLLABORATOR: 0
requiredLabels:
 - dependencies

rules:
  - requiredTitleRegex: '\bi3|digilines|digibuilder|basic_materials|moreblocks|mesecons|creative|digistuff|doors|dye|flowers|pipeworks|technic\b'

mergeMethod: rebase
reportStatus: true
