version: "3.6"

services:
 sut:
  image: registry.gitlab.com/minetest/minetest/server:${ENGINE_VERSION:-5.6.1}
  user: root
  volumes:
    - "./:/root/.minetest/games/mesecons_lab/"
    - "worlds:/root/.minetest/worlds/"
    - "./test/minetest.conf:/minetest.conf"
  ports:
    - "30000:30000/udp"
  entrypoint: ["minetestserver", "--config", "/minetest.conf"]

volumes:
  worlds: {}