version: "3.6"

services:
 sut:
  build: ./test
  user: root
  volumes:
    - "./:/root/.minetest/games/mesecons_lab/"
    - "worlds:/root/.minetest/worlds/"
  ports:
    - "30000:30000/udp"

volumes:
  worlds: {}