name: badges

on: [push]

jobs:
  badge_job:
    runs-on: ubuntu-latest
    name: Create badges
    steps:
      - uses: actions/checkout@v2
      - name: apt
        run: sudo apt-get install -y jq
      - id: size
        run: echo "##[set-output name=data;]$(cat mods/modgen_mod_export/manifest.json | jq .size/1000) kb"
      - id: mapblock_count
        run: echo "##[set-output name=data;]$(cat mods/modgen_mod_export/manifest.json | jq .mapblock_count)"
      - id: node_count
        run: echo "##[set-output name=data;]$(cat mods/modgen_mod_export/manifest.json | jq .next_id)"
      - name: Size badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: size
          LABEL: 'Modgen size'
          ICON: 'git'
          STATUS: ${{ steps.size.outputs.data }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Mapblock count badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: mapblock_count
          LABEL: 'Mapblocks'
          ICON: 'git'
          STATUS: ${{ steps.mapblock_count.outputs.data }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Node count badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: node_count
          LABEL: 'Unique nodes'
          ICON: 'git'
          STATUS: ${{ steps.node_count.outputs.data }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}