name: luacheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: apt
      run: sudo apt-get install -y luarocks
    - name: luacheck install
      run: luarocks install --local luacheck
    - name: luacheck run (mesecons_lab)
      run: cd mods/mesecons_lab && $HOME/.luarocks/bin/luacheck .
    - name: luacheck run (mesecons_lab_images)
      run: cd mods/mesecons_lab_images && $HOME/.luarocks/bin/luacheck .
